database:
    config:
      hostname: "localhost"
      port: "3306"
      username: "root"
      password: ""
      database: "minecraft"
RandomSpawn:
    XMin: -400
    XMax: 400
    ZMin: -400
    ZMax: 400