name: GamersNET
main: me.EggieCode.GamersNET.GNPlugin
version: 1.1
commands:
   RandomSpawn:
       description: Teleports you to a randon location
       usage: /randomspawn
   home:
       description: Home's
       usage: /home [args] [args]
   sethome:
       description: Home's
       usage: /sethome [args]